# Generated by Django 3.2.15 on 2022-09-20 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=50)),
                ('activo', models.CharField(choices=[('si', 'Y'), ('no', 'N')], max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ciudad',
                'verbose_name_plural': 'ciudades',
                'db_table': 'ciudades',
                'ordering': ['-ciudad'],
            },
        ),
        migrations.CreateModel(
            name='Entidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=70)),
                ('pais', models.CharField(choices=[('mx', 'México'), ('us', 'Estados Unidos')], max_length=20)),
                ('activo', models.CharField(choices=[('si', 'Y'), ('no', 'N')], default='si', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'entidad',
                'verbose_name_plural': 'entidades',
                'db_table': 'entidades',
                'ordering': ['-entidad'],
            },
        ),
        migrations.CreateModel(
            name='Locaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locacion', models.CharField(max_length=6)),
                ('locacion_name', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('codigo_postal', models.CharField(max_length=5)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('latitud', models.CharField(max_length=15)),
                ('longitud', models.CharField(max_length=15)),
                ('horario_apertura', models.TimeField()),
                ('horario_cierre', models.TimeField()),
                ('dias_operativos', models.CharField(max_length=21)),
                ('zona_ciudad', models.CharField(choices=[('cd', 'Ciudad'), ('apto', 'Aeropuerto')], max_length=5, verbose_name='Zona')),
                ('activo', models.CharField(choices=[('si', 'Y'), ('no', 'N')], max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('ciudades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.ciudades', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'locacion',
                'verbose_name_plural': 'locaciones',
                'db_table': 'locaciones',
                'ordering': ['-locacion'],
            },
        ),
        migrations.CreateModel(
            name='PuestosNominas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto_nomina', models.CharField(max_length=60)),
                ('activo', models.CharField(choices=[('si', 'Y'), ('no', 'N')], max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'puesto',
                'verbose_name_plural': 'puestos',
                'db_table': 'puestos_nominas',
                'ordering': ['-puesto_nomina'],
            },
        ),
        migrations.CreateModel(
            name='PuestosOperativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto_operativo', models.CharField(max_length=60)),
                ('canal_reclutamiento', models.CharField(choices=[('externo', 'Externo'), ('interno', 'Interno')], max_length=7)),
                ('activo', models.CharField(choices=[('si', 'Y'), ('no', 'N')], max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('puestos_nominas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.puestosnominas')),
            ],
            options={
                'verbose_name': 'puesto operativo',
                'verbose_name_plural': 'puestos operativos',
                'db_table': 'puestos_operativos',
                'ordering': ['-puesto_operativo'],
            },
        ),
        migrations.CreateModel(
            name='LocacionesPuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staf_requerido', models.IntegerField(blank=True, default=0, null=True)),
                ('staf_contratado', models.IntegerField(blank=True, default=0, null=True)),
                ('activo', models.CharField(choices=[('si', 'Y'), ('no', 'N')], max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('locaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.locaciones')),
                ('puestos_operativos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.puestosoperativos')),
            ],
            options={
                'verbose_name': 'locacione puesto',
                'verbose_name_plural': 'locaciones puestos',
                'db_table': 'locaciones_puestos',
                'ordering': ['-locaciones'],
            },
        ),
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('horario_inicio', models.TimeField()),
                ('horario_termino', models.TimeField()),
                ('dias_atencion', models.CharField(max_length=21)),
                ('activo', models.CharField(choices=[('si', 'Y'), ('no', 'N')], max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('locaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.locaciones')),
            ],
            options={
                'verbose_name': 'contacto',
                'verbose_name_plural': 'contactos',
                'db_table': 'contactos',
                'ordering': ['-contacto'],
            },
        ),
        migrations.AddField(
            model_name='ciudades',
            name='entidades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.entidades', verbose_name='Entidad'),
        ),
    ]
