# Generated by Django 3.2.15 on 2022-09-14 18:55

import configuraciones.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('horario_inicio', models.TimeField()),
                ('horario_termino', models.TimeField()),
                ('dias_atencion', models.CharField(max_length=21)),
                ('activo', models.CharField(choices=[(configuraciones.models.activo['si'], 'Y'), (configuraciones.models.activo['no'], 'N')], max_length=5)),
                ('created', models.DateField(auto_now_add=True)),
                ('updates', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'contacto',
                'verbose_name_plural': 'contactos',
                'db_table': 'contactos',
                'ordering': ['-contacto'],
            },
        ),
        migrations.CreateModel(
            name='Entidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=70)),
                ('contenido', models.TextField()),
                ('pais', models.CharField(choices=[(configuraciones.models.paises['mx'], 'México'), (configuraciones.models.paises['us'], 'Estados Unidos')], max_length=20)),
                ('activo', models.CharField(choices=[(configuraciones.models.activo['si'], 'Y'), (configuraciones.models.activo['no'], 'N')], max_length=20)),
                ('created', models.DateField(auto_now_add=True)),
                ('updates', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'entidad',
                'verbose_name_plural': 'entidades',
                'db_table': 'entidades',
                'ordering': ['-entidad'],
            },
        ),
        migrations.CreateModel(
            name='locaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locacion', models.CharField(max_length=6)),
                ('locacion_name', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('codigo_postal', models.CharField(max_length=5)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('latitud', models.CharField(max_length=15)),
                ('longitud', models.CharField(max_length=15)),
                ('horario_apertura', models.TimeField()),
                ('horario_cierre', models.TimeField()),
                ('dias_operativos', models.CharField(max_length=21)),
                ('zona_ciudad', models.CharField(choices=[(configuraciones.models.zonas_ciudades['cd'], 'Ciudad'), (configuraciones.models.zonas_ciudades['apto'], 'Aeropuerto')], max_length=5)),
                ('activo', models.CharField(choices=[(configuraciones.models.activo['si'], 'Y'), (configuraciones.models.activo['no'], 'N')], max_length=5)),
                ('created', models.DateField(auto_now_add=True)),
                ('updates', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'locacion',
                'verbose_name_plural': 'locaciones',
                'db_table': 'locaciones',
                'ordering': ['-locacion'],
            },
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=50)),
                ('activo', models.CharField(choices=[(configuraciones.models.activo['si'], 'Y'), (configuraciones.models.activo['no'], 'N')], max_length=5)),
                ('created', models.DateField(auto_now_add=True)),
                ('updates', models.DateField(auto_now_add=True)),
                ('entidades_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.entidades')),
            ],
            options={
                'verbose_name': 'ciudad',
                'verbose_name_plural': 'ciudades',
                'db_table': 'ciudades',
                'ordering': ['-ciudad'],
            },
        ),
    ]
