# Generated by Django 3.2.15 on 2022-09-14 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='locaciones_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuraciones.locaciones'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locaciones',
            name='ciudades_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuraciones.ciudades'),
            preserve_default=False,
        ),
    ]
