# Generated by Django 3.2.16 on 2022-10-11 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuraciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactos',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='contactos',
            name='dias_atencion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='locaciones',
            name='dias_operativos',
            field=models.CharField(max_length=50),
        ),
    ]
