# Generated by Django 3.2.15 on 2022-09-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudades',
            name='activo',
            field=models.CharField(choices=[('si', 'Y'), ('no', 'N')], default='si', max_length=5),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='activo',
            field=models.CharField(choices=[('si', 'Y'), ('no', 'N')], default='si', max_length=5),
        ),
        migrations.AlterField(
            model_name='entidades',
            name='pais',
            field=models.CharField(choices=[('mx', 'México'), ('us', 'Estados Unidos')], default='mx', max_length=20),
        ),
        migrations.AlterField(
            model_name='locaciones',
            name='activo',
            field=models.CharField(choices=[('si', 'Y'), ('no', 'N')], default='si', max_length=5),
        ),
        migrations.AlterField(
            model_name='locaciones',
            name='zona_ciudad',
            field=models.CharField(choices=[('cd', 'Ciudad'), ('apto', 'Aeropuerto')], default='apto', max_length=5, verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='locacionespuestos',
            name='activo',
            field=models.CharField(choices=[('si', 'Y'), ('no', 'N')], default='si', max_length=5),
        ),
        migrations.AlterField(
            model_name='puestosnominas',
            name='activo',
            field=models.CharField(choices=[('si', 'Y'), ('no', 'N')], default='si', max_length=5),
        ),
        migrations.AlterField(
            model_name='puestosoperativos',
            name='activo',
            field=models.CharField(choices=[('si', 'Y'), ('no', 'N')], default='si', max_length=5),
        ),
        migrations.AlterField(
            model_name='puestosoperativos',
            name='canal_reclutamiento',
            field=models.CharField(choices=[('externo', 'Externo'), ('interno', 'Interno')], default='externo', max_length=7),
        ),
    ]
