# Generated by Django 3.2.16 on 2022-11-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0002_auto_20221011_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='locaciones',
            name='indicaciones_entrevista',
            field=models.FileField(blank=True, null=True, upload_to='locaciones/indicaciones/'),
        ),
    ]
