# Generated by Django 3.2.15 on 2022-09-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0003_auto_20220922_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidades',
            name='activo',
            field=models.CharField(choices=[('Y', 'Si'), ('N', 'No')], default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='entidades',
            name='pais',
            field=models.CharField(choices=[('mx', 'México'), ('us', 'Estados Unidos')], default='mx', max_length=2),
        ),
    ]
