# Generated by Django 3.2.15 on 2022-09-14 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0003_auto_20220914_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciudades',
            old_name='updates',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='contactos',
            old_name='updates',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='entidades',
            old_name='updates',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='locaciones',
            old_name='updates',
            new_name='updated',
        ),
        migrations.RemoveField(
            model_name='entidades',
            name='contenido',
        ),
    ]
