# Generated by Django 3.2.16 on 2022-10-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0004_auto_20220922_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puestosoperativos',
            name='canal_reclutamiento',
            field=models.CharField(choices=[('externo', 'Externo'), ('interno', 'Interno')], default='externo', max_length=7, verbose_name='Reclutamiento'),
        ),
        migrations.AlterField(
            model_name='puestosoperativos',
            name='puesto_operativo',
            field=models.CharField(max_length=60, verbose_name='Puesto'),
        ),
    ]
