# Generated by Django 3.2.16 on 2022-11-24 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuraciones', '0004_auto_20221116_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacionespuestos',
            name='staf_autorizado',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Autorizado Contratar'),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='locacionespuestos',
            name='staf_contratado',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Staff Actual'),
        ),
        migrations.AlterField(
            model_name='locacionespuestos',
            name='staf_requerido',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Staff Requerido'),
        ),
    ]
