# Generated by Django 3.2.15 on 2022-09-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0005_auto_20220914_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudades',
            name='activo',
            field=models.CharField(choices=[('si', 'Y'), ('no', 'N')], max_length=5),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='activo',
            field=models.CharField(choices=[('si', 'Y'), ('no', 'N')], max_length=5),
        ),
        migrations.AlterField(
            model_name='entidades',
            name='activo',
            field=models.CharField(choices=[('si', 'Y'), ('no', 'N')], max_length=20),
        ),
        migrations.AlterField(
            model_name='entidades',
            name='pais',
            field=models.CharField(choices=[('mx', 'México'), ('us', 'Estados Unidos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='locaciones',
            name='activo',
            field=models.CharField(choices=[('si', 'Y'), ('no', 'N')], max_length=5),
        ),
        migrations.AlterField(
            model_name='locaciones',
            name='zona_ciudad',
            field=models.CharField(choices=[('cd', 'Ciudad'), ('apto', 'Aeropuerto')], max_length=5),
        ),
    ]
