# Generated by Django 3.2.15 on 2022-09-20 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0006_auto_20220914_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuestosNominas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto_nomina', models.CharField(max_length=60)),
                ('activo', models.CharField(choices=[('si', 'Y'), ('no', 'N')], max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'puesto',
                'verbose_name_plural': 'puestos',
                'db_table': 'puestos_nominas',
                'ordering': ['-puesto_nomina'],
            },
        ),
        migrations.AlterField(
            model_name='ciudades',
            name='entidades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.entidades', verbose_name='Entidad'),
        ),
        migrations.AlterField(
            model_name='entidades',
            name='activo',
            field=models.CharField(choices=[('si', 'Y'), ('no', 'N')], default='si', max_length=20),
        ),
        migrations.AlterField(
            model_name='locaciones',
            name='ciudades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.ciudades', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='locaciones',
            name='zona_ciudad',
            field=models.CharField(choices=[('cd', 'Ciudad'), ('apto', 'Aeropuerto')], max_length=5, verbose_name='Zona'),
        ),
        migrations.CreateModel(
            name='PuestosOperativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto_operativo', models.CharField(max_length=60)),
                ('canal_reclutamiento', models.CharField(choices=[('externo', 'Externo'), ('interno', 'Interno')], max_length=7)),
                ('activo', models.CharField(choices=[('si', 'Y'), ('no', 'N')], max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('puestos_nominas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.puestosnominas')),
            ],
            options={
                'verbose_name': 'puesto operativo',
                'verbose_name_plural': 'puestos operativos',
                'db_table': 'puestos_operativos',
                'ordering': ['-puesto_operativo'],
            },
        ),
        migrations.CreateModel(
            name='LocacionesPuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staf_requerido', models.IntegerField(blank=True, default=0, null=True)),
                ('activo', models.CharField(choices=[('si', 'Y'), ('no', 'N')], max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('locaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.locaciones')),
                ('puestos_operativos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.puestosoperativos')),
            ],
            options={
                'verbose_name': 'locacione puesto',
                'verbose_name_plural': 'locaciones puestos',
                'db_table': 'locaciones_puestos',
                'ordering': ['-locaciones'],
            },
        ),
    ]
