# Generated by Django 3.2.15 on 2022-09-16 00:30

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0007_auto_20220916_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='puestosnominas',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puestosnominas',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puestosoperativos',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puestosoperativos',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='puestosoperativos',
            name='locaciones',
            field=models.ManyToManyField(to='configuraciones.Locaciones'),
        ),
    ]
