# Generated by Django 3.2.15 on 2022-09-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0008_auto_20220916_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puestosoperativos',
            name='locaciones',
            field=models.ManyToManyField(to='configuraciones.Locaciones'),
        ),
    ]
