# Generated by Django 3.2.15 on 2022-09-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0009_alter_puestosoperativos_locaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puestosnominas',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='puestosnominas',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='puestosoperativos',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='puestosoperativos',
            name='locaciones',
            field=models.ManyToManyField(to='configuraciones.Locaciones'),
        ),
        migrations.AlterField(
            model_name='puestosoperativos',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
