# Generated by Django 3.2.16 on 2022-11-16 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes', '0013_auto_20221116_1629'),
        ('proveedores', '0003_auto_20221116_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('pre_factura_pdf', models.FileField(blank=True, null=True, upload_to='prefacturas/pdf', verbose_name='PDF Prefactura')),
                ('pre_factura_xml', models.FileField(blank=True, null=True, upload_to='prefacturas/xml', verbose_name='XML Prefactura')),
                ('factura_pdf', models.FileField(blank=True, null=True, upload_to='facturas/pdf', verbose_name='PDF Prefactura')),
                ('factura_xml', models.FileField(blank=True, null=True, upload_to='facturas/xml', verbose_name='XML Prefactura')),
                ('total_facturado', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('activo', models.CharField(choices=[('Y', 'Si'), ('N', 'No')], default='Y', max_length=1)),
                ('pagado', models.CharField(choices=[('Y', 'Si'), ('N', 'No')], default='Y', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('proveedores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedores', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'factura',
                'verbose_name_plural': 'facturas',
                'db_table': 'facturas',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='FacturasCandidatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(choices=[('Y', 'Si'), ('N', 'No')], default='Y', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('candidatos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.candidatos', verbose_name='Candidato')),
                ('facturas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.facturas', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'candidatos',
                'verbose_name_plural': 'candidatos',
                'db_table': 'facturas_candidatos',
            },
        ),
    ]
