# Generated by Django 3.2.16 on 2022-10-11 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuraciones', '0002_auto_20221011_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporte_entrevista', models.FileField(blank=True, null=True, upload_to='candidatos/personas/')),
                ('evalucion_psicometrica', models.FileField(blank=True, null=True, upload_to='candidatos/personas/')),
                ('aceptado', models.CharField(choices=[('Y', 'Si'), ('N', 'No')], default='Y', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'candidato',
                'verbose_name_plural': 'candidatos',
                'db_table': 'candidatos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(blank=True, max_length=70, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=300, null=True)),
                ('activo', models.CharField(choices=[('Y', 'Si'), ('N', 'No')], default='Y', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'db_table': 'documentos',
                'ordering': ['-documento'],
            },
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=250)),
                ('activo', models.CharField(choices=[('Y', 'Si'), ('N', 'No')], default='Y', max_length=1)),
                ('tipos', models.CharField(choices=[('solicitud', 'Solicitud'), ('candidato', 'Candidato')], default='Y', max_length=9)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'catalogo estatus',
                'verbose_name_plural': 'catalogos estatus',
                'db_table': 'calogos_estatus',
                'ordering': ['-estatus'],
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('rfc', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(max_length=15)),
                ('cv_solicitud', models.FileField(blank=True, null=True, upload_to='candidatos/personas/cv')),
                ('activo', models.CharField(choices=[('Y', 'Si'), ('N', 'No')], default='Y', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
                'db_table': 'personas',
                'ordering': ['-nombre'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudesVacantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suledos', models.DecimalField(decimal_places=2, max_digits=20)),
                ('comiciones', models.CharField(choices=[('Y', 'Si'), ('N', 'No')], default='Y', max_length=1)),
                ('bono', models.CharField(choices=[('Y', 'Si'), ('N', 'No')], default='Y', max_length=1)),
                ('garantia', models.CharField(choices=[('Y', 'Si'), ('N', 'No')], default='Y', max_length=1)),
                ('activo', models.CharField(choices=[('Y', 'Si'), ('N', 'No')], default='Y', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('locaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.locaciones', verbose_name='Locaciones')),
                ('locaciones_puestos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.locacionespuestos', verbose_name='Puestos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitud vacante',
                'verbose_name_plural': 'solicitudes vacantes',
                'db_table': 'solicitudes_vacantes',
                'ordering': ['-locaciones'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudesEstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(choices=[('Y', 'Si'), ('N', 'No')], default='Y', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.estatus', verbose_name='Estatus')),
                ('solicitudes_vacantes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitudesvacantes', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'solicitud estatus',
                'verbose_name_plural': 'solicitudes estatus',
                'db_table': 'solicitudes_estatus',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CandidatosEstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(choices=[('Y', 'Si'), ('N', 'No')], default='Y', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('candidatos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.candidatos', verbose_name='Candidatos')),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.estatus', verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'candidato estatus',
                'verbose_name_plural': 'candidatos estatus',
                'db_table': 'candidatos_estatus',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CandidatosDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_proveedor', models.CharField(choices=[('Y', 'Si'), ('N', 'No')], default='N', max_length=1)),
                ('check_locacion', models.CharField(choices=[('Y', 'Si'), ('N', 'No')], default='N', max_length=1)),
                ('candidatos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.candidatos', verbose_name='Candidatos')),
                ('documentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.documentos', verbose_name='Documentos')),
            ],
            options={
                'verbose_name': 'candidato documneto',
                'verbose_name_plural': 'Candidatos Documentos',
                'db_table': 'candidatos_documentos',
            },
        ),
        migrations.AddField(
            model_name='candidatos',
            name='personas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.personas', verbose_name='Personas'),
        ),
        migrations.AddField(
            model_name='candidatos',
            name='solicitudes_vacantes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitudesvacantes', verbose_name='Solicitudes'),
        ),
        migrations.AddField(
            model_name='candidatos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
