# Generated by Django 3.2.16 on 2022-10-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudesvacantes',
            old_name='suledos',
            new_name='sueldos',
        ),
        migrations.AddField(
            model_name='solicitudesvacantes',
            name='cantidad',
            field=models.IntegerField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
