# Generated by Django 3.2.16 on 2022-10-18 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0002_auto_20221011_1625'),
        ('solicitudes', '0003_solicitudesvacantes_periodo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudesvacantes',
            name='locaciones_puestos',
        ),
        migrations.AddField(
            model_name='solicitudesvacantes',
            name='puestos_operativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuraciones.puestosoperativos', verbose_name='Puestos'),
        ),
        migrations.AlterField(
            model_name='solicitudesvacantes',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='solicitudesvacantes',
            name='periodo_pago',
            field=models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('catorcenal', 'Catorcenal'), ('mensual', 'Mensual')], default='quincenal', max_length=10),
        ),
    ]
