# Generated by Django 3.2.16 on 2022-10-18 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_auto_20221018_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatos',
            old_name='evalucion_psicometrica',
            new_name='evaluacion_psicometrica',
        ),
    ]
