# Generated by Django 3.2.16 on 2022-10-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_rename_evalucion_psicometrica_candidatos_evaluacion_psicometrica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas',
            name='cv_solicitud',
        ),
        migrations.AddField(
            model_name='candidatos',
            name='cv_solicitud',
            field=models.FileField(blank=True, null=True, upload_to='candidatos/personas/cv'),
        ),
    ]
