# Generated by Django 3.2.16 on 2022-10-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_auto_20221021_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentos',
            options={'ordering': ['created'], 'verbose_name': 'documento', 'verbose_name_plural': 'documentos'},
        ),
        migrations.AddField(
            model_name='documentos',
            name='consideraciones',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('gerencial', 'Gerencial')], default='requerido', max_length=9),
        ),
        migrations.AlterField(
            model_name='candidatosdocumentos',
            name='check_locacion',
            field=models.CharField(blank=True, choices=[('Y', 'Si'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='candidatosdocumentos',
            name='check_proveedor',
            field=models.CharField(blank=True, choices=[('Y', 'Si'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='estatus',
            name='tipos',
            field=models.CharField(choices=[('solicitud', 'Solicitud'), ('candidato', 'Candidato')], default='solicitud', max_length=9),
        ),
    ]
