# Generated by Django 3.2.16 on 2022-11-02 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_auto_20221031_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estatus',
            options={'ordering': ['created'], 'verbose_name': 'catalogo estatus', 'verbose_name_plural': 'catalogos estatus'},
        ),
        migrations.AddField(
            model_name='candidatos',
            name='referencias',
            field=models.FileField(blank=True, null=True, upload_to='candidatos/referencias/'),
        ),
        migrations.CreateModel(
            name='Entrevistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicaciones', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fecha_programada', models.DateField()),
                ('hora_programada', models.TimeField()),
                ('fecha_entrevista', models.DateField()),
                ('asistio', models.CharField(choices=[('Y', 'Si'), ('N', 'No')], default='Y', max_length=1)),
                ('candidatos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.candidatos', verbose_name='Candidatos')),
            ],
            options={
                'verbose_name': 'entrevista',
                'verbose_name_plural': 'entrevistas',
                'db_table': 'entrevistas',
                'ordering': ['-created'],
            },
        ),
    ]
