# Generated by Django 3.2.16 on 2022-11-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0008_auto_20221102_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrevistas',
            name='asistio',
            field=models.CharField(blank=True, choices=[('Y', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='entrevistas',
            name='fecha_entrevista',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrevistas',
            name='indicaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
