# Generated by Django 3.2.16 on 2022-11-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0009_auto_20221103_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('I', 'Indistinto')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='rfc',
            field=models.CharField(max_length=20, unique=True, verbose_name='RFC'),
        ),
    ]
