# Generated by Django 3.2.16 on 2022-11-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0011_auto_20221114_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrevistas',
            options={'verbose_name': 'entrevista', 'verbose_name_plural': 'entrevistas'},
        ),
        migrations.AddField(
            model_name='entrevistas',
            name='tipo_evento',
            field=models.CharField(choices=[('entrevista', 'Entrevista'), ('contratacion', 'Contratacion')], default='entrevista', max_length=12),
        ),
    ]
