# Generated by Django 3.2.16 on 2022-11-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0013_auto_20221116_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatos',
            name='tipo_candidato',
            field=models.CharField(choices=[('normal', 'Normal'), ('garantia', 'Garantia')], default='normal', max_length=8),
        ),
        migrations.AlterField(
            model_name='entrevistas',
            name='tipo_evento',
            field=models.CharField(choices=[('entrevista', 'Entrevista'), ('contratacion', 'Contratacion'), ('ingreso', 'Ingreso')], default='entrevista', max_length=12),
        ),
    ]
