# Generated by Django 3.2.16 on 2022-12-02 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0014_auto_20221130_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivosRechazos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_rechazo', models.CharField(max_length=100)),
                ('activo', models.CharField(choices=[('Y', 'Si'), ('N', 'No')], default='Y', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'motivo rechazo',
                'verbose_name_plural': 'motivos rechazos',
                'db_table': 'motivos_rechazos',
            },
        ),
        migrations.AlterModelOptions(
            name='solicitudesvacantes',
            options={'verbose_name': 'solicitud vacante', 'verbose_name_plural': 'solicitudes vacantes'},
        ),
        migrations.AddField(
            model_name='candidatosestatus',
            name='motivos_rechazos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.motivosrechazos', verbose_name='Motivo de Rechazo'),
        ),
    ]
