# Generated by Django 3.2.16 on 2022-12-02 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0015_auto_20221202_2244'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estatus',
            table='catalogos_estatus',
        ),
    ]
