# Generated by Django 3.2.16 on 2022-12-05 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0016_alter_estatus_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatos',
            name='candidato_sustituye',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.candidatos', verbose_name='Candidato Sustituye'),
        ),
    ]
