# Generated by Django 3.2.16 on 2022-12-08 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0017_candidatos_candidato_sustituye'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivosrechazos',
            name='tipos',
            field=models.CharField(choices=[('solicitud', 'Solicitud'), ('candidato', 'Candidato')], default='candidato', max_length=9),
        ),
        migrations.AddField(
            model_name='solicitudesestatus',
            name='motivos_rechazos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.motivosrechazos', verbose_name='Motivo de Rechazo'),
        ),
    ]
