# Generated by Django 3.2.16 on 2023-01-06 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_auto_20221116_1629'),
        ('solicitudes', '0018_auto_20221208_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentos',
            options={'ordering': ['created'], 'verbose_name': 'documento', 'verbose_name_plural': 'Catalogo documentos'},
        ),
        migrations.AlterModelOptions(
            name='motivosrechazos',
            options={'verbose_name': 'motivo rechazo', 'verbose_name_plural': 'catalogo motivos rechazos'},
        ),
        migrations.AddField(
            model_name='solicitudesvacantes',
            name='proveedores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedores', verbose_name='Proveedores'),
        ),
    ]
