# Generated by Django 3.2.15 on 2022-09-16 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=70)),
                ('rfc', models.CharField(max_length=13)),
                ('razon_social', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=5, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.CharField(choices=[('Y', 'Si'), ('N', 'No')], default='Y', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'db_table': 'proveedores',
                'ordering': ['-proveedor'],
            },
        ),
        migrations.CreateModel(
            name='ContactosProveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto_nombre', models.CharField(max_length=70)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tipo_contacto', models.CharField(choices=[('P', 'Principal'), ('A', 'Asociado')], default='A', max_length=1)),
                ('activo', models.CharField(choices=[('Y', 'Si'), ('N', 'No')], default='Y', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('proveedores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedores', verbose_name='Proveedros')),
            ],
            options={
                'verbose_name': 'contacto proveedor',
                'verbose_name_plural': 'contactos proveedores',
                'db_table': 'contactos_proveedores',
                'ordering': ['-contacto_nombre'],
            },
        ),
    ]
