# Generated by Django 3.2.16 on 2022-10-11 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactosproveedores',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='contactosproveedores',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
