# Generated by Django 3.2.15 on 2022-09-21 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0002_auto_20220921_1848'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactosproveedores',
            name='proveedores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedores', verbose_name='Proveedores'),
        ),
        migrations.CreateModel(
            name='LocacionesProveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(choices=[('Y', 'Si'), ('N', 'No')], default='Y', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('locaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.locaciones', verbose_name='Locaciones')),
                ('proveedores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedores', verbose_name='Proveedores')),
            ],
            options={
                'verbose_name': 'locacion proveedor',
                'verbose_name_plural': 'locaciones proveedores',
                'db_table': 'locaciones_proveedores',
                'ordering': ['-locaciones'],
            },
        ),
    ]
