# Generated by Django 3.2.16 on 2022-10-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_auto_20220921_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactosproveedores',
            options={'ordering': ['-activo'], 'verbose_name': 'contacto proveedor', 'verbose_name_plural': 'contactos proveedores'},
        ),
        migrations.RemoveField(
            model_name='contactosproveedores',
            name='contacto_nombre',
        ),
        migrations.RemoveField(
            model_name='contactosproveedores',
            name='email',
        ),
    ]
